-- MySQL Script generated by MySQL Workbench
-- Thu May  2 18:31:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema irobot_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema irobot_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `irobot_db` DEFAULT CHARACTER SET utf8 ;
USE `irobot_db` ;

-- -----------------------------------------------------
-- Table `irobot_db`.`Anschrift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irobot_db`.`Anschrift` ;

CREATE TABLE IF NOT EXISTS `irobot_db`.`Anschrift` (
  `idAnschrift` INT NOT NULL,
  `Straße` VARCHAR(45) NULL,
  `Nr` INT NULL,
  `PLZ` INT NULL,
  `Ort` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnschrift`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `irobot_db`.`Benutzer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irobot_db`.`Benutzer` ;

CREATE TABLE IF NOT EXISTS `irobot_db`.`Benutzer` (
  `idBenutzer` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Vorname` VARCHAR(45) NULL,
  `Passwort` VARCHAR(45) NULL,
  `Anschrift_idAnschrift` INT NOT NULL,
  PRIMARY KEY (`idBenutzer`),
  CONSTRAINT `fk_Benutzer_Anschrift1`
    FOREIGN KEY (`Anschrift_idAnschrift`)
    REFERENCES `irobot_db`.`Anschrift` (`idAnschrift`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `irobot_db`.`Bestellung`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irobot_db`.`Bestellung` ;

CREATE TABLE IF NOT EXISTS `irobot_db`.`Bestellung` (
  `idBestellung` INT NOT NULL,
  `Datum` VARCHAR(45) NULL,
  `Benutzer_idBenutzer` INT NOT NULL,
  `Benutzer_Anschrift_idAnschrift` INT NOT NULL,
  PRIMARY KEY (`idBestellung`),
  CONSTRAINT `fk_Bestellung_Benutzer1`
    FOREIGN KEY (`Benutzer_idBenutzer`)
    REFERENCES `irobot_db`.`Benutzer` (`idBenutzer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `irobot_db`.`Artikel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irobot_db`.`Artikel` ;

CREATE TABLE IF NOT EXISTS `irobot_db`.`Artikel` (
  `idArtikel` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Beschreibung` VARCHAR(255) NULL,
  `Kategorie` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtikel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `irobot_db`.`Bestellposition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irobot_db`.`Bestellposition` ;

CREATE TABLE IF NOT EXISTS `irobot_db`.`Bestellposition` (
  `Anzahl` INT NOT NULL,
  `Bestellung_idBestellung` INT NOT NULL,
  `Artikel_idArtikel` INT NOT NULL,
  PRIMARY KEY (`Anzahl`),
  CONSTRAINT `fk_Bestellposition_Bestellung1`
    FOREIGN KEY (`Bestellung_idBestellung`)
    REFERENCES `irobot_db`.`Bestellung` (`idBestellung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellposition_Artikel1`
    FOREIGN KEY (`Artikel_idArtikel`)
    REFERENCES `irobot_db`.`Artikel` (`idArtikel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `irobot_db`.`Variante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irobot_db`.`Variante` ;

CREATE TABLE IF NOT EXISTS `irobot_db`.`Variante` (
  `idVariante` INT NOT NULL,
  `Farbe` VARCHAR(45) NULL,
  `Akkukapazität` INT NULL,
  `Preis` DECIMAL(20) NULL,
  `Artikel_idArtikel` INT NOT NULL,
  PRIMARY KEY (`idVariante`),
  CONSTRAINT `fk_Variante_Artikel1`
    FOREIGN KEY (`Artikel_idArtikel`)
    REFERENCES `irobot_db`.`Artikel` (`idArtikel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
